# Generated by Django 3.0.4 on 2020-04-03 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_client_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='proposals',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='user',
        ),
        migrations.AddField(
            model_name='proposal',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='proposal', to='api.Client'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contract',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='contracts', to='api.Proposal'),
        ),
    ]
